package com.example.platform.modules.qa.controller;

import com.example.platform.common.response.ApiResponse;
import com.example.platform.modules.qa.dto.response.QaEmbeddingResponse;
import com.example.platform.modules.qa.service.QaEmbeddingReadService;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * Exposes read-only API endpoints for QA embedding metadata.
 * Returns model and vector status without exposing the full embedding payload.
 *
 * <p>Used for checking stored semantic-search vectors.
 * Base path: /api/qa-embeddings | Phase 1: Read only | Response wrapper: ApiResponse</p>
 *
 * @author Mobina
 * @see com.example.platform.modules.qa.service.QaEmbeddingReadService
 */
@RestController
@RequiredArgsConstructor
@RequestMapping("/api/qa-embeddings")
public class QaEmbeddingController {

    private final QaEmbeddingReadService qaEmbeddingReadService;

    /**
     * Return all embedding metadata records.
     */
    @GetMapping("/all")
    public ApiResponse<List<QaEmbeddingResponse>> getAllEmbeddings() {
        return ApiResponse.ok(qaEmbeddingReadService.getAllEmbeddings());
    }

    /**
     * Return embedding metadata by embedding id.
     */
    @GetMapping("/{id}")
    public ApiResponse<QaEmbeddingResponse> getEmbeddingById(@PathVariable Integer id) {
        return ApiResponse.ok(qaEmbeddingReadService.getEmbeddingById(id));
    }

    /**
     * Return embedding metadata for a specific QA pair.
     */
    @GetMapping("/by-qa/{qaId}")
    public ApiResponse<QaEmbeddingResponse> getEmbeddingByQaId(@PathVariable Integer qaId) {
        return ApiResponse.ok(qaEmbeddingReadService.getEmbeddingByQaId(qaId));
    }

    /**
     * Return embeddings generated by a specific model.
     */
    @GetMapping("/by-model")
    public ApiResponse<List<QaEmbeddingResponse>> getEmbeddingsByModelName(@RequestParam String modelName) {
        return ApiResponse.ok(qaEmbeddingReadService.getEmbeddingsByModelName(modelName));
    }

    /**
     * Return total number of embeddings.
     */
    @GetMapping("/count")
    public ApiResponse<Long> countEmbeddings() {
        return ApiResponse.ok(qaEmbeddingReadService.countEmbeddings());
    }

    /**
     * Check whether a QA pair has an embedding.
     */
    @GetMapping("/exists")
    public ApiResponse<Boolean> existsByQaId(@RequestParam Integer qaId) {
        return ApiResponse.ok(qaEmbeddingReadService.existsByQaId(qaId));
    }
}
