package com.example.platform.modules.qa.model;

import jakarta.persistence.*;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.SuperBuilder;

/**
 * Represents a user intent category for classifying QA pairs.
 * Examples: "course_inquiry", "price_inquiry", "teacher_inquiry".
 *
 * <p>Used by IntentService for keyword-based intent detection.
 * DB: intents | Phase 1: Read only | PK: id (Integer)</p>
 *
 * @author Mobina
 * @see QaIntent
 */
@Getter
@Setter
@SuperBuilder
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Entity(name = "intentEntity")
@Table(name = "intents")
public class Intent {
    /**
     * Primary key generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * Unique intent name used for filtering QA pairs.
     */
    @Column(name = "name", nullable = false, unique = true, columnDefinition = "TEXT")
    private String name;

    // Phase 1 keeps created_at unmapped in Java.
//    @CreatedDate
//    @Column(name = "created_at", updatable = false)
//    private LocalDateTime createdAt;

}
