package com.example.platform.modules.qa.model;

import jakarta.persistence.*;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.SuperBuilder;

/**
 * Represents a stored embedding vector for a QA pair.
 * Each row keeps the semantic vector and the model that generated it.
 *
 * <p>Used by semantic search to compare user questions with prepared QA pairs.
 * DB: qa_embeddings | Phase 1: Read/Search only | Relation: one-to-one with QaPair</p>
 *
 * @author Mobina
 * @see QaPair
 */
@Getter
@Setter
@SuperBuilder
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Entity(name = "qaEmbeddingEntity")
@Table(name = "qa_embeddings")
public class QaEmbedding {

    /**
     * Primary key generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * Each embedding belongs to exactly one QA pair.
     */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "qa_id", unique = true, nullable = false)
    private QaPair qaPair;

    /**
     * Stored pgvector value; returned only as metadata in responses.
     */
    @Column(columnDefinition = "vector(384)", nullable = false)
    private String embedding;

    /**
     * Embedding model name for traceability.
     */
    @Column(name = "model_name", nullable = false)
    private String modelName;

    // Phase 1 keeps created_at unmapped in Java.
//    @CreatedDate
//    @Column(name = "created_at", updatable = false)
//    private LocalDateTime createdAt;
}

