package com.example.platform.modules.qa.model;

import com.example.platform.modules.course.model.Course;
import jakarta.persistence.*;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.SuperBuilder;

/**
 * Represents a prepared question-answer pair for the chatbot.
 * Stores the source question, final answer, and optional related course.
 *
 * <p>Used by QA services for keyword search, detail view, and semantic candidates.
 * DB: qa_pairs | Phase 1: Read/Search only | PK: id (Integer)</p>
 *
 * @author Mobina
 * @see QaEmbedding
 * @see QaIntent
 */
@Getter
@Setter
@SuperBuilder
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Entity(name = "qa_pairEntity")
@Table(name = "qa_pairs")
public class QaPair {

    /**
     * Primary key generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * Unique source question used for keyword matching.
     */
    @Column(name = "question", nullable = false, unique = true, columnDefinition = "TEXT")
    private String question;

    /**
     * Prepared answer returned to the chatbot pipeline.
     */
    @Column(name = "answer", nullable = false, columnDefinition = "TEXT")
    private String answer;

    /**
     * Optional course context for this QA pair.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "course_id", nullable = true)
    private Course course;

    // Phase 1 keeps created_at unmapped in Java.
//    @CreatedDate
//    @Column(name = "created_at", updatable = false)
//    private LocalDateTime created_at;
}

