package com.example.platform.common.entity;

import jakarta.persistence.Column;
import jakarta.persistence.MappedSuperclass;

import java.time.OffsetDateTime;

/**
 * Base class for entities that have a created_at column.
 *
 * The value is generated by PostgreSQL using DEFAULT NOW()
 * in Flyway migrations, so Hibernate should not insert or update this column.
 *
 * Use this class only for tables that actually have created_at.
 */
@MappedSuperclass
public abstract class CreatedAtEntity extends BaseEntity {

    @Column(name = "created_at", nullable = false, insertable = false, updatable = false)
    private OffsetDateTime createdAt;

    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }
}